djcrm/urls.py
"""
URL configuration for djcrm project.
"""
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignUpView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetConfirmView, 
    PasswordResetDoneView,
    PasswordResetCompleteView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", LandingPageView.as_view(), name="landing_page"),
    path('leads/', include("leads.urls"), name="leads"),
    path('agents/', include("agents.urls"), name="agents"),

    # Reset password URLs
    path("reset_password/", PasswordResetView.as_view(), name="reset_password"),
    path("password_reset_done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset_complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    
    # Authentication URLs
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"
urlpatterns = [
    path("", views.LeadIndexView.as_view(), name="index"),
    path("<int:pk>/", views.LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/assign_agent", views.AssignAgentView.as_view(), name="assign_agent"),
    path("<int:pk>/category", views.LeadCategoryUpdateView.as_view(), name="lead_category_update"),
    path("create/", views.LeadCreateView.as_view(), name="lead_create"),
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("categories/<int:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    organization_name = models.CharField(max_length=100, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}"


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="leads")
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL,  related_name="assigned_leads")
    category = models.ForeignKey("Category", null=True, blank=True, on_delete=models.SET_NULL, related_name="leads")
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.age})"


class Category(models.Model):
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="categories")

    def __str__(self):
        return self.name

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="agent_profile")
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="agents")

    def __str__(self):
        return self.user.email
    

def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model
from .models import Lead, Agent

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
            'description',
            'phone_number',
            'email',
        )
        


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {
            "username": UsernameField,
        }

class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        print(kwargs)
        super().__init__(*args, **kwargs)

        # Filter to only show leads under the user's organization
        agents = Agent.objects.filter(organization=request.user.profile)
        self.fields["agent"].queryset = agents
        
class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )

leads/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Lead
from django.views import generic
from .forms import LeadForm, LeadModelForm, CustomUserCreationForm, AssignAgentForm, LeadCategoryUpdateForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from agents.mixins import OrganizerAndLoginRequiredMixin



# My class-based views.
class SignUpView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

class LandingPageView(generic.TemplateView):
    template_name = "landing.html"  

class LeadIndexView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/index.html"
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user
        
        # If the user is an organizer, show all leads in their organization
        if user.is_organizer:
            queryset = user.profile.leads.filter(
                agent__isnull=False  # Only show leads that have an agent assigned
            )

        # Filter leads by the agent associated with the logged-in user
        else:
            agent = user.agent_profile
            queryset = agent.assigned_leads.all()
            
        return queryset
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        user = self.request.user

        # Filter for unassigned leads
        if user.is_organizer:
            queryset = user.profile.leads.filter(
                agent__isnull=True
            )
            context.update({
                "unassigned_leads": queryset,
            })

        return context
        

class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        agent = user.agent_profile
        
        # If the user is an organizer, show all leads in their organization
        if user.is_organizer:
            queryset = user.profile.leads.all()

        # Filter leads by the agent associated with the logged-in user
        else:
            queryset = agent.assigned_leads.all()
            
        return queryset

class LeadCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def form_valid(self, form):
        user = self.request.user
        lead = form.save(commit=False)
        lead.organization = user.profile  # Set the organization to the user's profile
        lead.save()
        messages.success(self.request, "Lead created successfully!")
        send_mail(
            subject="A new lead has been created",
            message="Go to the admin panel to view the lead.",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse("leads:index")
    
class LeadUpdateView(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        
        # Show all leads in their organization
        queryset = user.profile.leads.all()
            
        return queryset
    
    def form_valid(self, form):
        messages.success(self.request, "Lead updated successfully!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("leads:index")

class LeadDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "leads/lead_delete.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        
        # Initial queryset of all leads in their organization
        queryset = Lead.objects.filter(organization=user.profile)
            
        return queryset
    
    def form_valid(self, form):
        messages.success(self.request, "Lead successfully deleted!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("leads:index")
    
class AssignAgentView(OrganizerAndLoginRequiredMixin, generic.FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request

        return kwargs
    
    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        messages.success(self.request, f"You have successfully assigned agent {agent.user.username} to {lead.first_name}")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("leads:index")

class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/category_list.html"
    context_object_name = "categories"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        agent = user.agent_profile

        if user.is_organizer:
            queryset = user.profile.leads.all()
        else:
            queryset = agent.organization.categories.all()
 
        context.update({
            "unassigned_lead_count": queryset.filter(category__isnull=True).count()
        })

        return context

    def get_queryset(self):
        user = self.request.user

        # Return queryset category of leads under user's organization
        if user.is_organizer:
            queryset = user.profile.categories.all()
        else:
            queryset = user.agent_profile.organization.categories.all()

        return queryset

class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        category = self.get_object()  

        # Get leads in this category
        if user.is_organizer:
            leads = category.leads.filter(organization=user.profile)
        else:
            leads = category.leads.filter(organization=user.agent_profile.organization)

        context.update({
            "leads": leads,
        })

        return context

    def get_queryset(self):
        user = self.request.user

        # Return queryset category of leads under user's organization
        if user.is_organizer:
            queryset = user.profile.categories.all()
        else:
            queryset = user.agent_profile.organization.categories.all()

        return queryset
    
class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        
        # Return queryset of leads under user's organization
        if user.is_organizer:
            queryset = user.profile.leads.all()
        else:
            agent = user.agent_profile
            queryset = agent.assigned_leads.all()
            
        return queryset
    
    def form_valid(self, form):
        messages.success(self.request, "Lead category updated successfully!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("leads:lead_detail", kwargs={"pk": self.get_object().pk})

# My function-based views.

def landing_page(request):
    return render(request, "landing.html")

def index(request):
    leads = Lead.objects.all()

    return render(request, "leads/index.html", {
        "leads": leads,
    })

def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)


    return render(request, "leads/lead_detail.html", {
        "lead": lead,
    })

def lead_create(request):
    form = LeadModelForm()

    if request.method == "POST":
        form = LeadModelForm(request.POST)

        # Validate form
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("leads:index"))
    return render(request, "leads/lead_create.html", {
        "form": form
    })

def lead_update(request, pk):

    # Set form instance
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)

    # Update data of lead instance
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance=lead)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse("leads:index"))

    return render(request, "leads/lead_update.html", {
        "lead": lead,
        "form": form,
    })

def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return HttpResponseRedirect(reverse("leads:index"))
    
    
# end def



# def lead_create(request):
#     form = LeadForm()

#     if request.method == "POST":
#         form = LeadForm(request.POST)

#         # Validate form
#         if form.is_valid():
#             print("The form is valid")
#             print(form.cleaned_data)
#             first_name = form.cleaned_data["first_name"]
#             last_name = form.cleaned_data["last_name"]
#             age = form.cleaned_data["age"]
#             agent = Agent.objects.first()

#             # Create the new lead in the database
#             Lead.objects.create(
#                 first_name=first_name,
#                 last_name=last_name,
#                 age=age,
#                 agent=agent
#             )

leads/templates/leads/assign_agent.html
{% extends "layout.html" %}

{% block title %}
    Assign agent
{% endblock title %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        <div class="container mx-auto px-4 py-8">
            <h2 class="text-2xl font-bold mb-6">Assign an agent to lead</h2>
            {{ form.as_p }}
            <button type="submit" class="bg-indigo-500 text-white px-4 py-2 my-3 rounded hover:bg-indigo-600">
                Assign
            </button>
        </div>
    </form>
{% endblock body %}

leads/templates/leads/category_list.html
{% extends "layout.html" %}

{% block title %}
    Categories
{% endblock title %}

{% block body %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex flex-col text-center w-full mb-20">
                <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
                <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                    These are the categories of leads that you can create. Each category can have its own set of fields and properties.
                </p>
            </div>
            <div class="lg:w-2/3 w-full mx-auto overflow-auto">
                <table class="table-auto w-full text-left whitespace-no-wrap">
                    <thead>
                        <tr>
                            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
                            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="px-4 py-3">Unassigned</td>
                            <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
                        </tr>
                        {% for category in categories %}
                            <tr>
                                <td class="px-4 py-3">
                                <a class="hover:text-purple-400" href="{% url "leads:category_detail" category.pk %}">{{ category.name }}</a></td>
                                <td class="px-4 py-3">TODO: Count</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="flex pl-4 mt-4 lg:w-2/3 w-full mx-auto">
                <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">
                    Learn More
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </a>
            </div>
        </div>
    </section>
{% endblock body %}

leads/templates/leads/index.html
{% extends "layout.html" %}

{% block title %}
    CRM
{% endblock title %}

{% block body %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-dark-200">
                        Leads
                    </h1>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category_list' %}">
                        View categories
                    </a>
                </div>
                {% if request.user.is_organizer %}
                    <div>
                        <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead_create' %}">
                            Create a new lead
                        </a>
                    </div>
                {% endif %}
            </div>

            <div class="flex flex-wrap m-4">

                {% for lead in leads %}
                
                    <div class="p-4 lg:w-1/2 md:w-full">
                        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                    <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                            </div>
                            <div class="flex-grow">
                                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                    {{ lead.first_name }} {{ lead.last_name }}
                                </h2>
                                <p class="leading-relaxed text-base">
                                    Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
                                </p>
                                <a href="{% url 'leads:lead_detail' lead.id %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                    View this lead
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>

            {% if unassigned_leads.exists %}
                <div class="flex flex-wrap m-4">
                    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                        <div>
                            <h1 class="text-4xl text-dark-200">
                                Unassigned Leads
                            </h1>
                        </div>
                    </div>

                    {% for lead in unassigned_leads %}
                    
                        <div class="p-4 lg:w-1/2 md:w-full">
                            <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                                        <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                        <circle cx="12" cy="7" r="4"></circle>
                                    </svg>
                                </div>
                                <div class="flex-grow">
                                    <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                        {{ lead.first_name }} {{ lead.last_name }}
                                    </h2>
                                    <p class="leading-relaxed text-base">
                                        Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
                                    </p>
                                    <a href="{% url 'leads:assign_agent' lead.id %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                        Assign an agent to lead
                                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                </div>
            {% endif %}
        </div>
    </section>


{% endblock body %}

leads/templates/leads/lead_category_update.html
{% extends "layout.html" %}
{% load tailwind_filters %}


{% block title %}
    Update Lead Data
{% endblock title %}

{% block body %}
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="mx-auto flex flex-wrap">
                <div class="w-full lg:pr-10 lg:py-6 mb-6">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">
                        LEAD 
                    </h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                        {{ lead.first_name }} {{ lead.last_name }} 
                    </h1>
                    <div class="flex mb-4">
                        <a href="{% url "leads:lead_detail" lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Overview
                        </a>
                        <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                           Category
                        </a>
                        <a href="{% url "leads:lead_update" lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Update Details
                        </a>
                    </div>
                   <form action="#" method="post">
                        {% csrf_token %}    
                        {{ form|crispy }} 
                        <div class="mt-3 flex justify-between">
                            <div>
                                <a href="{% url 'leads:lead_delete' lead.id %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                                    Delete This Lead
                                </a>
                            </div>
                            <div>
                                <input class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit" value="Save Changes">  
                            </div>
                        </div>                                           
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock body %}

leads/templates/leads/lead_detail.html
{% extends "layout.html" %}

{% block title %}
    Lead Detail
{% endblock title %}

{% block body %}
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="mx-auto flex flex-wrap">
                <div class="w-full lg:pr-10 lg:py-6 mb-6">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">
                        LEAD 
                    </h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                        {{ lead.first_name }} {{ lead.last_name }} 
                    </h1>
                    <div class="flex mb-4">
                        <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                            Overview
                        </a>
                        <a href="{% url "leads:lead_category_update" lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Category
                        </a>
                        <a href="{% url 'leads:lead_update' lead.id%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Update Details
                        </a>
                    </div>
                    <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Age</span>
                        <span class="ml-auto text-gray-900">{{ lead.age }}</span>
                    </div>
                        <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Location</span>
                        <span class="ml-auto text-gray-900">Dummy Location</span>
                    </div>
                    <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                        <span class="text-gray-500">Cell Phone</span>
                        <span class="ml-auto text-gray-900">+233 23 2344 2134</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
{% endblock body %}

leads/templates/leads/lead_update.html
{% extends "layout.html" %}
{% load tailwind_filters %}


{% block title %}
    Update Lead Data
{% endblock title %}

{% block body %}
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="mx-auto flex flex-wrap">
                <div class="w-full lg:pr-10 lg:py-6 mb-6">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">
                        LEAD 
                    </h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                        {{ lead.first_name }} {{ lead.last_name }} 
                    </h1>
                    <div class="flex mb-4">
                        <a href="{% url 'leads:lead_detail' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Overview
                        </a>
                        <a href="{% url "leads:lead_category_update" lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Category
                        </a>
                        <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                           Update Details
                        </a>
                    </div>
                   <form action="#" method="post">
                        {% csrf_token %}    
                        {{ form|crispy }} 
                        <div class="mt-3 flex justify-between">
                            <div>
                                <a href="{% url 'leads:lead_delete' lead.id %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                                    Delete This Lead
                                </a>
                            </div>
                            <div>
                                <input class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit" value="Save Changes">  
                            </div>
                        </div>                                           
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock body %}