agents/urls.py
from django.urls import path
from . import views

app_name = "agents"

urlpatterns = [
    path("", views.AgentListView.as_view(), name="agent_list"),
    path("create/", views.AgentCreateView.as_view(), name="agent_create"),
    path("<int:pk>/", views.AgentDetailView.as_view(), name="agent_detail"),
    path("<int:pk>/update/", views.AgentUpdateView.as_view(), name="agent_update"),
    path("<int:pk>/delete/", views.AgentDeleteView.as_view(), name="agent_delete"),    
]

djcrm/urls.py
"""
URL configuration for djcrm project.
"""
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignUpView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetConfirmView, 
    PasswordResetDoneView,
    PasswordResetCompleteView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", LandingPageView.as_view(), name="landing_page"),
    path('leads/', include("leads.urls"), name="leads"),
    path('agents/', include("agents.urls"), name="agents"),

    # Reset password URLs
    path("reset_password/", PasswordResetView.as_view(), name="reset_password"),
    path("password_reset_done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset_complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    
    # Authentication URLs
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from leads.models import Agent
from django.contrib.auth import get_user_model

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
        )
        

agents/views.py
import random

from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganizerAndLoginRequiredMixin
from django.core.mail import send_mail



class AgentListView(OrganizerAndLoginRequiredMixin, generic.ListView):
    """
    View to list all agents.
    Requires the user to be logged in.
    """
    model = Agent
    template_name = "agents/agent_list.html"
    context_object_name = "agents"

    def get_queryset(self):
        request_user_organization = self.request.user.profile
        return self.model.objects.filter(organization=request_user_organization)
    

class AgentCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    """
    View to create a new agent.
    Requires the user to be logged in.
    """
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse("agents:agent_list")
    
    def form_valid(self, form):
        
        # Create user and set the user as an agent
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organizer = False
        user.set_password(f"{random.randint(0, 10000000)}")
        user.save()

        # Create agent instance and associate it with the user's organization
        Agent.objects.create(
            user=user,
            organization=self.request.user.profile
        )

        # Send mail to the new agent 
        send_mail(
            subject="You are invited to be an agent",
            message="You have been added as an agent in our system. Please log in to your account to start working.", 
            from_email="admin@test.com",
            recipient_list=[user.email],
        )

        messages.success(self.request, "Agent created successfully!")

        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganizerAndLoginRequiredMixin, generic.DetailView):
    """
    View to display details of a specific agent.
    Requires the user to be logged in.
    """
    model = Agent
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        request_user_organization = self.request.user.profile
        return self.model.objects.filter(organization=request_user_organization)

class AgentUpdateView(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    """
    View to update an existing agent.
    Requires the user to be logged in.
    """
    template_name = "agents/agent_update.html"
    context_object_name = "agent"
    form_class = AgentModelForm

    def get_queryset(self):
        user = self.request.user
        return user.profile.agents.all()

    def form_valid(self, form):
        messages.success(self.request, "Agent update successful!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("agents:agent_list")

    
class AgentDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    """
    View to delete an existing agent.
    Requires the user to be logged in.
    """
    model = Agent
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"

    def get_queryset(self):
        request_user_organization = self.request.user.profile
        return self.model.objects.filter(organization=request_user_organization)
    
    
    def get_success_url(self):
        return reverse("agents:agent_list")
    

agents/templates/agents/agent_create.html
{% extends "layout.html" %}
{% load tailwind_filters %}

{% block title %}
    Create New Agent
{% endblock title %}

{% block body %}
    <form method="post">
    {% csrf_token %}
        <div class="container max-w-lg mx-auto px-4 py-8 bg-black-500 shadow-lg rounded-lg">
            <a class="hover:text-blue-500" href="{% url 'agents:agent_list' %}">Go back to agents</a>
            <hr>     
            <h2 class="text-2xl font-bold mb-6 mt-5">Create a new lead</h2>
            {{ form|crispy }}
            <button type="submit" class="bg-indigo-500 text-white px-4 py-2 rounded hover:bg-indigo-600">Submit</button>
        </div>
    </form>
{% endblock body %}

agents/templates/agents/agent_delete.html
{% extends "layout.html" %}
{% load tailwind_filters %}


{% block title %}
    Delete Agent
{% endblock title %}

{% block body %}
    <section class="text-gray-600 body-font">
        <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
            <div class="text-center lg:w-2/3 w-full">
                <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                    Delete Agent: {{ agent.user.username }}
                </h1>
                <p class="mb-8 leading-relaxed">
                    Are you sure you want to delete this agent? This action cannot be undone.
                </p>
                <div class="flex justify-center">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <a href="{% url 'agents:agent_list' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                            Cancel
                        </a>
                        <button type="submit" class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
                            Delete
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock body %}

agents/templates/agents/agent_detail.html
{% extends "layout.html" %}

{% block title %}
    Agent Detail
{% endblock title %}

{% block body %}
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="mx-auto flex flex-wrap">
                <div class="w-full lg:pr-10 lg:py-6 mb-6">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">
                        AGENT 
                    </h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                        {{ agent.user.username }}
                    </h1>
                    <div class="flex mb-4">
                        <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                            Overview
                        </a>
                        <a href="{% url 'agents:agent_update' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                            Update Details
                        </a>
                    </div>
                    <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Age</span>
                        <span class="ml-auto text-gray-900">None for now</span>
                    </div>
                        <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Location</span>
                        <span class="ml-auto text-gray-900">Dummy Location</span>
                    </div>
                    <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                        <span class="text-gray-500">Cell Phone</span>
                        <span class="ml-auto text-gray-900">+233 23 2344 2134</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
{% endblock body %}

agents/templates/agents/agent_list.html
{% extends "layout.html" %}

{% block title %}
    Agents
{% endblock %}

{% block body %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-dark-200">
                        Agents
                    </h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent_create' %}">
                        Create a new agent
                    </a>
                </div>
            </div>

            <div class="flex flex-wrap -m-4">

            {% for agent in agents %}
            
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                <circle cx="12" cy="7" r="4"></circle>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ agent.user.username }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
                            </p>
                            <a href="{% url 'agents:agent_detail' agent.id %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                View this agent
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>

            {% endfor %}
            </div>
        </div>
    </section>
{% endblock body %}

agents/templates/agents/agent_update.html
{% extends "layout.html" %}
{% load tailwind_filters %}

{% block title %}
    Update Agent Data
{% endblock title %}

{% block body %}
    <section class="text-gray-600 w-full body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class=" w-full lg:pr-10 lg:py-6 mb-6">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">
                    Agent 
                </h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                    {{ agent.user.username }} 
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'agents:agent_detail' agent.id%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <form method="post">
                    {% csrf_token %}    
                    {{ form|crispy }} 
                    <div class="mt-3 flex justify-between">
                        <div>
                            <a href="{% url 'agents:agent_delete' agent.id %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                                Delete This Agent
                            </a>
                        </div>
                        <div>
                            <input class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit" value="Save Changes">  
                        </div>
                    </div>                                           
                </form>
            </div>
        </div>
    </section>
{% endblock body %}