agents/urls.py
from django.urls import path
from . import views

app_name = "agents"

urlpatterns = [
    path("", views.AgentListView.as_view(), name="agent_list"),
    path("create/", views.AgentCreateView.as_view(), name="agent_create"),
    path("<int:pk>/", views.AgentDetailView.as_view(), name="agent_detail"),
    path("<int:pk>/update/", views.AgentUpdateView.as_view(), name="agent_update"),
    path("<int:pk>/delete/", views.AgentDeleteView.as_view(), name="agent_delete"),    
]

djcrm/urls.py
"""
URL configuration for djcrm project.
"""
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignUpView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetConfirmView, 
    PasswordResetDoneView,
    PasswordResetCompleteView
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", LandingPageView.as_view(), name="landing_page"),
    path('leads/', include("leads.urls"), name="leads"),
    path('agents/', include("agents.urls"), name="agents"),

    # Reset password URLs
    path("reset_password/", PasswordResetView.as_view(), name="reset_password"),
    path("password_reset_done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset_complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    
    # Authentication URLs
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"
urlpatterns = [
    path("", views.LeadIndexView.as_view(), name="index"),
    path("<int:pk>/", views.LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/assign_agent", views.AssignAgentView.as_view(), name="assign_agent"),
    path("<int:pk>/category", views.LeadCategoryUpdateView.as_view(), name="lead_category_update"),
    path("create/", views.LeadCreateView.as_view(), name="lead_create"),
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("categories/<int:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),
]

templates/landing.html
{% extends "layout.html" %}

{% block title %}
Home Page
{% endblock title %}

{% block body %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
        <div class="text-center lg:w-2/3 w-full">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                Customer Relationship Manager(CRM) built with Django
            </h1>
            <p class="mb-8 leading-relaxed">
                This CRM helps you manage your leads.
            </p>
            <div class="flex justify-center">
                <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
                <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
            </div>
        </div>
    </div>
</section>
{% endblock body %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <style type="text/tailwindcss">
      @theme {
        --color-clifford: #da373d;
      }
    </style>
</head>
<body>
    <div class="max-v-7xl mx-auto">
        {% include 'navbar.html' %}

        {% if messages %}
			<div class="space-y-3 px-4 py-2">
				{% for message in messages %}
					<div 
						x-data="{ show: true }"
						x-init="setTimeout(() => show = false, 4000)" 
						x-show="show"
						x-transition
						class="rounded-lg p-4 text-sm font-medium
								{% if message.tags == 'success' %}
								bg-green-100 text-green-800
								{% elif message.tags == 'error' %}
								bg-red-100 text-red-800
								{% elif message.tags == 'warning' %}
								bg-yellow-100 text-yellow-800
								{% elif message.tags == 'info' %}
								bg-blue-100 text-blue-800
								{% else %}
								bg-gray-100 text-gray-800
								{% endif %}">
						{{ message }}
                	</div>
              	{% endfor %}
            </div>
        {% endif %}


        {% block body %}
        {% endblock body %}

        {% include "scripts.html" %}
    </div>
</body>
</html> 

templates/navbar.html
<header class="text-gray-600 body-font">
<div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
            <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">
            CRM
        </span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% if request.user.is_authenticated %}
            <a href="{% url 'leads:index' %}" class="mr-5 hover:text-gray-900">
                Leads
            </a>
            {% if request.user.is_organizer %}
                <a href="{% url 'agents:agent_list' %}" class="mr-5 hover:text-gray-900">
                    Agents
                </a>
            {% endif %}
        {% else %}
            <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">
                Sign Up
            </a>     
        {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
        Logged in as: {{ request.user.username }}
        <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
            <button type="submit" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
                Logout
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
            </button>
        </form>
    {% else %}
        <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Login
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
    {% endif %}
</div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static "js/main.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>